apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: medical-system
data:
  NODE_ENV: "production"
  PORT: "3000"
  LOG_LEVEL: "info"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX: "100"
