apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-appointments-api
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medical-appointments-api
  template:
    metadata:
      labels:
        app: medical-appointments-api
    spec:
      containers:
      - name: medical-appointments-api
        image: medical-appointments-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: medical-appointments-api-service
spec:
  selector:
    app: medical-appointments-api
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer