apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: medical-system
type: Opaque
data:
  # Estos valores están codificados en base64
  # mongodb://username:password@hostname:port/database
  uri: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQG1vbmdvZGI6MjcwMTcvbWVkaWNpdGFz
  
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: medical-system
type: Opaque
data:
  # Estos valores están codificados en base64
  secret: bWVkaWNpdGFzLWFwaS1zZWN1cmUtand0LXNlY3JldC1rZXk=
