apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: medical-system
spec:
  selector:
    app: medical-appointments-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
  type: ClusterIP
